---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint --exclude molecule --offline
platforms:
  - name: datadog-lynis-ubuntu-1604
    image: ubuntu:16.04
  - name: datadog-lynis-ubuntu-1804
    image: ubuntu:18.04
  - name: datadog-lynis-ubuntu-2004
    image: ubuntu:20.04
  - name: datadog-lynis-debian-buster
    image: debian:buster
  - name: datadog-lynis-debian-stretch
    image: debian:stretch
  - name: datadog-lynis-debian-jessie
    image: debian:jessie
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
